### ISSUE TITLE
TypeError: context is not a function in binding.js

### ISSUE THREAD

**Issue by pfurini** [jdanyow/aurelia-computed#12]
Hi
I'm opening an issue here, following up the issue aurelia/binding#252, to report a problem of the aurelia-computed plugin that impacts the aurelia binding engine.

I had an Aurelia project fully tested and working with October release, that included the following packages:
- aurelia-bootstrapper
- aurelia-breeze
- **aurelia-computed**
- aurelia-event-aggregator
- aurelia-framework
- aurelia-http-client
- aurelia-logging
- aurelia-router

Made a copy and updated to latest Aurelia beta 1 release, including the latest release of aurelia-computed. The update has been done by wiping jspm_packages and reinstalling for scratch, just to be safe..
Since updating, the new codebase started to fail on some random bindings with the error `TypeError: context is not a function` in binding.js.
First I removed every reference to the `aureliaComputed` attribute, and relative imports. Same errors, probably the auto detection of dependants was kicking in and causing failures in the core binding engine.
Then I removed the aurelia-computed package from the project, and everything started to work flawlessly.. No more random errors in the binding engine.

There's definitely something wrong with the latest published **aurelia-computed** package, at least in combination with the latest **aurelia-binding** release.

Please see my comment here: https://github.com/aurelia/binding/issues/252#issuecomment-163579788
The error always come up from the last loop in the `callSubscribers` function, as I stated in that comment. 
I can't say for sure if it is a valid but edge case, that the core binding code doesn't handle correctly, or if it is the aurelia-computed code that generates invalid binding instructions...

**Comment by Mordred** [comment]
I'm also getting this error when _aurelia-computed_ is activated in my project.

**Comment by jdanyow** [comment]
sorry guys- will get this fixed tonight
