### ISSUE TITLE
Error with webpack skeleton

### ISSUE THREAD

**Issue by darianferrer** [jdanyow/aurelia-computed#15]
Hi, 
I'm trying to install this plugin with the webpack skeleton navigation app but it fails when I run `npm run build`, it says 'Module not found: Error: cannot resolve module aurelia-computed'.

**Comment by alu** [comment]
I think there is small mistake at package.json in this repository.
The main file defined [here](https://github.com/jdanyow/aurelia-computed/blob/master/package.json#L16), but the real main file is `dist/commonjs/aurelia-computed.js`.

**Comment by jdanyow** [comment]
fixed in v1.0.0
