### ISSUE TITLE
Allow replacing handler

### ISSUE THREAD

**Issue by atsu85** [jdanyow/aurelia-computed#19]
Currently reporting is hard-coded with logger:
`logger.debug(`Unable to observe '${propertyName}'.  ${info.reason}`);`

It would be nice to be able to replace it so i could for example throw error in dev mode and in production report it for example through Bugsnag or smth like that.

**Comment by jdanyow** [comment]
In v1.0.0 you can pass in a function via the `writeLog` property of the config.  Function is called with `propertyName` and `reason` args.

**Comment by atsu85** [comment]
thanks, I was about to send a PR for this feature :D

Confirming, that it works as expected
