### ISSUE TITLE
simple getter not working

### ISSUE THREAD

**Issue by avrahamcool** [jdanyow/aurelia-computed#20]
I have a simple getter like that:
```
export class App
{
  firstName;
  lastName;
  get fullName()
  {
    console.log(new Date());
    return this.firstName + " " + this.lastName;
  }
}
```

then, when running the app I get:
```
DEBUG [aurelia-computed] Unable to observe 'fullName'.  Unable to parse 'fullName' property's getter function.
function get() {
        console.log(new Date());
        return this.firstName + " " + this.lastName;
      }
```

and then aurelia uses `dirty checking`.

removing the `console.log` lines make it work.
but I want to use this library for even more complex getters, and using functions inside the getter seems to break it.

**Comment by jdanyow** [comment]
please see: https://github.com/jdanyow/aurelia-computed/blob/master/README.md

use the `@computedFrom` decorator that ships with aurelia for more complex scenarios.
