### ISSUE TITLE
Plugin configured too late

### ISSUE THREAD

**Issue by simonfox** [jdanyow/aurelia-computed#8]
I'm seeing an issue due to the order of aurelia plugin installation and the way in which this plugin installs itself.

In short, the `ObserverLocator` is getting created before the aurelia-computed plugin is installed, and so the `ObservationAdapter` the plugin installs isn't yet registered and the `ObserverLocator` gets created without it included in the `All.of(ObjectObservationAdapter)` ctor parameter.

I've traced it to creation of the `SyntaxInterpreter` of templating-binding - the `ObserverLocator` dependency being satisfied.

I feel like I must be doing something wrong, but not sure where to start looking? My configuration isn't particularly complicated....

``` js
export function configure(aurelia) {
    aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-computed')
    .plugin('aurelia-animator-css')
    .plugin('aurelia-validation', config => {
      config.values.viewStrategy.searchFormGroup = ValidationCustomizations.searchFormGroup;
    })
    .plugin('aurelia-dialog')
    .plugin('bootstrap')
    .plugin('aurelia-widgets')
    .feature('widgets/time-picker')
    .feature('widgets/duration')
    .feature('widgets/nav-bar')
    .feature('widgets/spot-selector')
    .feature('widgets/loading-indicator');
```

I can workaround with the following hack....

``` js
  let adapter = new ComputedObservationAdapter(aurelia.container);
  let observerLocator = aurelia.container.get(ObserverLocator);
  observerLocator.observationAdapters.push(adapter);
```

**Comment by jdanyow** [comment]
@simonfox thanks for reporting this and the workaround.  Will try and get this fixed in the next aurelia release.

**Comment by simonfox** [comment]
@jdanyow I was going to offer to help with a fix but your on to it already!! Thank you!!
